In [12]:
#1

import numpy as np

array = np.array([10, 20, 30, 40])
print(array)

[10 20 30 40]


In [14]:
#2

import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
#3

import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#4

import numpy as np

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
#5

import numpy as np

ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#6

import numpy as np

array = np.linspace(1, 10, 5)
print(array)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
#7

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped = array.reshape(2, 3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [20]:
#8

import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d[1, 1])

4


In [21]:
#9

import numpy as np
array = np.array([10, 20, 30, 40, 50])
sliced_array = array[:2]
print(sliced_array)

[10 20]


In [22]:
#10

import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d[:, 1])

[2 4 6]


In [23]:
#11

import numpy as np

array = np.array([1, 2, 3, 4, 5])
new_array = array + 10
print(new_array)

[11 12 13 14 15]


In [24]:
#12

import numpy as np

array = np.array([1, 2, 3, 4, 5])

filterd_array = array[array > 3]
print(filterd_array)

[4 5]


In [25]:
#13

import numpy as np

array1 = np.array([1, 2])
array2 = np.array([3, 4])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[1 2]
 [3 4]]


In [27]:
#14

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
split_array = np.split(array, 2)
print(split_array)



[array([1, 2, 3]), array([4, 5, 6])]


In [28]:
#15

import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
column_sum = np.sum(array_2d, axis=0)
print(column_sum)

[ 9 12]


In [1]:
#2

import numpy as np

array1d = np.array([1, 2, 3])
print(array1d)

array2d = np.array([[1, 2], [3, 4]])
print(array2d)

[1 2 3]
[[1 2]
 [3 4]]


In [3]:
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
array = np.array([1, 2, 3], dtype='float32')
print(array)

[1. 2. 3.]


In [5]:
#3 - Indexing

array = np.array([10, 20, 30, 40])
print(array[1])

array2d = np.array([[1, 2], [3, 4]])
print(array2d[1, 1])

20
4


In [6]:
#3 - Slicing

array = np.array([10, 20, 30, 40, 50])
print(array[1:4])

array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d[:, 1])

[20 30 40]
[2 5]


In [7]:
#3 - Boolean Indexing

array = np.array([10, 20, 30, 40])
print(array[array > 20])

[30 40]


In [9]:
#4 - Reshaping

array = np.arange(6)
reshaped = array.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [10]:
#4 - Stacking

a = np.array([1, 2])
b = np.array([3, 4])

vstacked = np.vstack((a, b))
print(vstacked)

hstacked = np.hstack((a, b))
print(hstacked)

[[1 2]
 [3 4]]
[1 2 3 4]


In [11]:
#4 - Splitting

array = np.arange(6).reshape(2, 3)
print(np.hsplit(array, 3))

[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]
