In [1]:
#1

import numpy as np

array = np.array([5, 10, 15, 20, 25])
print(array)

[ 5 10 15 20 25]


In [2]:
#2

import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
#3

import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#4

import numpy as np

array = np.arange(10, 101, 10)
print(array)

[ 10  20  30  40  50  60  70  80  90 100]


In [10]:
#5

import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
#6

import numpy as np

array = np.linspace(1, 100, 10)
print(array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [12]:
#7

import numpy as np

array = np.array([3, 6, 9])
new_array = array * 3
print(new_array)

[ 9 18 27]


In [13]:
#8
import numpy as np

array2d = np.array([[1, 2], [3, 4]])
print(array2d[1, 0])

3


In [15]:
#9
import numpy as np

array = np.array([2, 4, 6, 8, 10])
print(array[:3])

[2 4 6]


In [16]:
#10

import numpy as np

random_array = np.random.randint(1, 101, 10)
print(random_array)


[34 75 54 96  5 84 10 53 24 87]
