In [1]:
#1

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [8]:
#2

import numpy as np

random_int_matrix = np.random.randint(0, 2, (3, 3))
print(random_int_matrix)

[[0 1 1]
 [1 0 0]
 [0 0 0]]


In [5]:
#3

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]


In [6]:
#4

import numpy as np

zeros_matrix = np.zeros((2, 3))
updated_matrix = zeros_matrix + 10
print(updated_matrix)

[[10. 10. 10.]
 [10. 10. 10.]]


In [7]:
#5

import numpy as np

array = np.array([1, 2, 3, 4, 5])
cumsum_array = np.cumsum(array)
print(cumsum_array)

[ 1  3  6 10 15]


In [9]:
#6

import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

print(a + b)

[[ 5  7  9]
 [ 8 10 12]]


In [10]:
#7

import numpy as np

random_int_matrix = np.random.randint(1, 100, (4, 4))
print(random_int_matrix)
print(np.min(random_int_matrix))
print(np.max(random_int_matrix))

[[89 48 44 31]
 [39 80  9 71]
 [29 63 92  9]
 [ 8 83 40 90]]
8
92


In [11]:
#8

import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
#9

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filtered_array = array[array > 5]
print(filtered_array)

[ 6  7  8  9 10]


In [16]:
#10

import numpy as np

random_matrix = np.random.rand(5, 5)
#print(random_matrix)

transpose_a = np.transpose(random_matrix)
print(transpose_a)

[[0.44126178 0.05119528 0.24930525 0.92982962 0.86158906]
 [0.57937146 0.72518711 0.83961908 0.95315885 0.91629964]
 [0.9793995  0.74933482 0.17593645 0.68250951 0.22539306]
 [0.45123414 0.94268373 0.5524058  0.58632234 0.24177353]
 [0.82517862 0.8915637  0.65792064 0.47263226 0.41577271]]
