In [1]:
#1

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [2]:
#2

import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))

15


In [3]:
#3

import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(np.mean(array))
print(np.std(array))

3.0
1.4142135623730951


In [5]:
#4

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]


In [6]:
#5

import numpy as np

random_matrix = np.random.rand(5, 5)
print(random_matrix)

[[0.37656254 0.87332818 0.45367132 0.9002242  0.41371613]
 [0.9746901  0.32508449 0.10151893 0.82980909 0.00936106]
 [0.21608604 0.92089594 0.77281721 0.80795805 0.11135421]
 [0.68721726 0.31425332 0.77389571 0.4474056  0.13359218]
 [0.51183563 0.37081406 0.07224001 0.78901341 0.62183045]]


In [7]:
#6

import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#7

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)

[ 4 10 18]


In [9]:
#8

import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

print(a + b)

[[ 5  7  9]
 [ 8 10 12]]


In [10]:
#9

import numpy as np

zeros_matrix = np.zeros((3, 3))
updated_matrix = zeros_matrix + 5
print(updated_matrix)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [11]:
#10

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
split_array = np.split(array, 3)
print(split_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
#11
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
filtered_array = array[array % 2 == 0]
print(filtered_array)

[2 4 6]


In [14]:
#12

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
print(dot_product)

32


In [16]:
#13

import numpy as np

array = np.array([1, 2, 3, 4, 5])
cumsum_array = np.cumsum(array)
print(cumsum_array)

[ 1  3  6 10 15]


In [18]:
#14

import numpy as np

random_int_matrix = np.random.randint(1, 100, (4, 4))
print(random_int_matrix)

[[55 29  8 78]
 [55 77 38 74]
 [49 98 97 49]
 [68 51 70 54]]


In [19]:
#15

import numpy as np

a = np.array([[1, 2], [3, 4]])
transpose_a = np.transpose(a)
print(transpose_a)

[[1 3]
 [2 4]]
