In [15]:
#solution of problem-01

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('employees_large.csv')

average_salary = df.groupby('Department')['Salary'].mean().reset_index()

highest_salary_department = average_salary.loc[average_salary['Salary'].idxmax()]

print("Average Salary by Department:")
print(average_salary)

print(f"\nDepartment: {highest_salary_department['Department']}, Average Salary: {highest_salary_department['Salary']}")



Average Salary by Department:
    Department    Salary
0  Engineering  125000.0
1      Finance   78000.0
2           HR   68000.0
3           IT   57750.0
4    Marketing   43750.0

Department: Engineering, Average Salary: 125000.0


In [18]:
#solution of problem-01

import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/My Drive/221002339_Nahid_Python(EDGE)/221002339_FinalExam_Python-EDGE/employees_large.csv'

df = pd.read_csv(file_path)

average_salary = df.groupby('Department')['Salary'].mean().reset_index()

highest_salary_department = average_salary.loc[average_salary['Salary'].idxmax()]

print("Average Salary by Department:")
print(average_salary)

print(f"\nDepartment: {highest_salary_department['Department']}, Average Salary: {highest_salary_department['Salary']}")


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Average Salary by Department:
    Department    Salary
0  Engineering  125000.0
1      Finance   78000.0
2           HR   68000.0
3           IT   57750.0
4    Marketing   43750.0

Department: Engineering, Average Salary: 125000.0


In [13]:
#solution of problem-02

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('sales_large.csv')

total_sales = df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

product_sales = df.groupby('Product')['Sales'].sum()
highest_selling_product = product_sales.idxmax()
highest_sales_value = product_sales.max()

print("Total Sales by Region and Product:")
print(total_sales)

print(f"\nProduct: {highest_selling_product}, Total Sales: {highest_sales_value}")


Saving sales_large.csv to sales_large (1).csv
Total Sales by Region and Product:
     Region  Product  Sales
0   Central   Apples   9000
1   Central  Oranges   8000
2      East   Apples   5000
3      East  Bananas   8500
4      East  Oranges  13900
5     North   Apples   7200
6     North  Bananas   9000
7     North  Oranges   4900
8     South   Apples  12900
9     South  Bananas   5100
10    South  Oranges   3000
11     West   Apples  18900
12     West  Bananas  14700
13     West  Oranges   7500

Product: Apples, Total Sales: 53000


In [19]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/My Drive/221002339_Nahid_Python(EDGE)/221002339_FinalExam_Python-EDGE/sales_large.csv'

df = pd.read_csv(file_path)

total_sales = df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

product_sales = df.groupby('Product')['Sales'].sum()
highest_selling_product = product_sales.idxmax()
highest_sales_value = product_sales.max()

print("Total Sales by Region and Product:")
print(total_sales)

print(f"\nProduct: {highest_selling_product}, Total Sales: {highest_sales_value}")


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Total Sales by Region and Product:
     Region  Product  Sales
0   Central   Apples   9000
1   Central  Oranges   8000
2      East   Apples   5000
3      East  Bananas   8500
4      East  Oranges  13900
5     North   Apples   7200
6     North  Bananas   9000
7     North  Oranges   4900
8     South   Apples  12900
9     South  Bananas   5100
10    South  Oranges   3000
11     West   Apples  18900
12     West  Bananas  14700
13     West  Oranges   7500

Product: Apples, Total Sales: 53000


In [11]:
#solution of problem-03

import numpy as np

A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

sum_matrix = A + B
elementwise_product = A * B
dot_product = np.dot(A, B.T)
determinant_A = np.linalg.det(A)

print("Element-wise Sum:\n", sum_matrix)
print("\nElement-wise Product:\n", elementwise_product)
print("\nDot Product of A and B^T:\n", dot_product)
print("\nDeterminant of A:", determinant_A)



Element-wise Sum:
 [[10  9  8]
 [ 8  7  6]
 [13 12 11]]

Element-wise Product:
 [[16 20 12]
 [ 7 12  5]
 [42 27  0]]

Dot Product of A and B^T:
 [[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]

Determinant of A: 0.0


In [3]:
#solution of problem-04

import numpy as np

data = np.random.randn(10000)

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

min_val = np.min(data)
max_val = np.max(data)

count_greater_than_mean = np.sum(data > mean_val)

normalized_data = (data - min_val) / (max_val - min_val)


print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Standard Deviation: {std_dev}\n")
print(f"Minimum Value: {min_val}")
print(f"Maximum Value: {max_val}\n")
print(f"Count of values greater than mean: {count_greater_than_mean}\n")
print(f"First 5 normalized values: {normalized_data[:5]}")


Mean: -0.00801873498042217
Median: -0.012821071151406186
Standard Deviation: 1.0065508672802073

Minimum Value: -3.7558347993811454
Maximum Value: 4.045594923421932

Count of values greater than mean: 4981

First 5 normalized values: [0.41573976 0.4966546  0.50312372 0.63403271 0.64543484]


In [10]:
#solution of problem-05

temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26,
                31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]

above_32 = [temp for temp in temperatures if temp > 32]

classified_temps = [(temp, "Hot" if temp > 35 else "Warm" if 30 <= temp <= 35 else "Cool") for temp in temperatures]

average_temp = sum(temperatures) / len(temperatures)
temp_differences = [temp - average_temp for temp in temperatures]

print("Temperatures above 32°C:", above_32)
print("\nTemperature Classification (First 5 shown):", classified_temps[:5])
print("\nTemperature Differences from Monthly Average (First 5 shown):", temp_differences[:5])


Temperatures above 32°C: [35, 33, 36, 34, 37, 38, 35, 33, 36, 34, 35, 33]

Temperature Classification (First 5 shown): [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool')]

Temperature Differences from Monthly Average (First 5 shown): [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335]
